export {
  BrowserHermesTransport,
  HermesBackendUnavailableError,
  createHermesTransport,
  type CreateHermesTransportOptions,
} from "./transport"
export { HermesRpcError, JsonRpcGatewayClient, isMethodNotFound, type RpcClientOptions } from "./rpc-client"
export {
  emptyHermesEventState,
  contentToText,
  pendingPromptFromEvent,
  reduceHermesEventState,
  toolActivityFromEvent,
  type HermesEventState,
} from "./normalize"
export {
  negotiateHttpFallback,
  parseSse,
  stopHttpFallbackRun,
  streamHttpFallback,
  type HttpFallbackKind,
  type HttpFallbackPrompt,
  type HttpFallbackSelection,
  type HttpStreamEvent,
} from "./http-fallback"
export {
  HERMES_DESKTOP_CONTRACT,
  HERMES_MIN_GATEWAY_CONTRACT,
  type Attachment,
  type AttachmentInput,
  type AutomationJob,
  type AutomationOutput,
  type AutomationRun,
  type BackendMode,
  type BackendState,
  type BootstrapInfo,
  type CapabilitySet,
  type CommandResult,
  type ContextBreakdown,
  type ConnectionState,
  type HermesEvent,
  type HermesEventName,
  type HermesTransport,
  type Message,
  type MessageRole,
  type ModelOption,
  type LearningNode,
  type PendingPrompt,
  type PendingWrite,
  type ProjectNode,
  type ProjectTreePayload,
  type RollbackCheckpoint,
  type RollbackDiff,
  type RollbackRestoreResult,
  type SendOptions,
  type SessionCreateInput,
  type SessionIdentity,
  type SessionListOptions,
  type SessionMessageHistory,
  type SessionResumeOptions,
  type SessionRuntimeInfo,
  type SessionSnapshot,
  type SessionSummary,
  type SessionSearchHit,
  type SessionUndoResult,
  type ToolActivity,
  type UsageStats,
  type WorkspaceEntry,
} from "./types"
