export {
  BrowserHermesTransport,
  HermesBackendUnavailableError,
  createHermesTransport,
  type CreateHermesTransportOptions,
} from "./transport"
export { HermesRpcError, JsonRpcGatewayClient, isMethodNotFound, type RpcClientOptions } from "./rpc-client"
export {
  commandCatalogSchema,
  commandDispatchDirectiveSchema,
  commandPairSchema,
  liveSessionStatusSchema,
  rawActiveSessionItemSchema,
  rawActiveSessionListSchema,
  slashCompletionItemSchema,
  slashCompletionResultSchema,
  slashExecResponseSchema,
} from "./schemas"
export {
  emptyHermesEventState,
  contentToText,
  normalizeActiveSessionItem,
  pendingPromptFromEvent,
  reduceHermesEventState,
  toolActivityFromEvent,
  type HermesEventState,
} from "./normalize"
export {
  negotiateHttpFallback,
  parseSse,
  stopHttpFallbackRun,
  streamHttpFallback,
  type HttpFallbackKind,
  type HttpFallbackPrompt,
  type HttpFallbackSelection,
  type HttpStreamEvent,
} from "./http-fallback"
export {
  HERMES_DESKTOP_CONTRACT,
  HERMES_MIN_GATEWAY_CONTRACT,
  type ActiveSessionItem,
  type ActiveSessionSummary,
  type Attachment,
  type AttachmentInput,
  type AutomationJob,
  type AutomationOutput,
  type AutomationRun,
  type BackendMode,
  type BackendState,
  type BootstrapInfo,
  type CapabilitySet,
  type CommandCatalog,
  type CommandCategory,
  type CommandExecutionResult,
  type CommandExecutionSource,
  type CommandPair,
  type CommandResult,
  type ContextBreakdown,
  type ConnectionState,
  type HermesEvent,
  type HermesEventName,
  type HermesTransport,
  type Message,
  type MessageRole,
  type ModelOption,
  type LearningNode,
  type LiveSessionStatus,
  type PendingPrompt,
  type PendingWrite,
  type ProjectNode,
  type ProjectTreePayload,
  type RollbackCheckpoint,
  type RollbackDiff,
  type RollbackRestoreResult,
  type SendOptions,
  type SessionCreateInput,
  type SessionIdentity,
  type SessionListOptions,
  type SessionMessageHistory,
  type SessionResumeOptions,
  type SessionRuntimeInfo,
  type SessionSnapshot,
  type SessionSummary,
  type SessionSearchHit,
  type SessionUndoResult,
  type SlashCompletionItem,
  type SlashCompletionResult,
  type ToolActivity,
  type UsageStats,
  type WorkspaceEntry,
} from "./types"
